export const ROLE_OPTIONS = [
  "Student",
  "Software engineer",
  "Designer",
  "Data / analyst",
  "Product manager",
  "Non-technical founder",
  "Already a founder",
];

export const SKILL_OPTIONS = [
  // ── Engineering ──────────────────────────────────────────────────────────
  "Software engineering",
  "Frontend development",
  "Backend development",
  "Full-stack development",
  "Mobile development (iOS / Android)",
  "iOS / Swift development",
  "Android / Kotlin development",
  "React / Next.js",
  "Vue / Nuxt",
  "Python development",
  "Rust / systems programming",
  "Go development",
  "Ruby / Rails",
  "PHP / Laravel",
  "Java / Spring",
  ".NET / C# development",
  "TypeScript",
  "Data science / ML",
  "Machine learning engineering",
  "LLM / AI engineering",
  "Computer vision",
  "NLP engineering",
  "Prompt engineering",
  "DevOps / cloud infrastructure",
  "Kubernetes / container orchestration",
  "Infrastructure as code (Terraform)",
  "AWS / GCP / Azure",
  "Database design / DBA",
  "SQL / database queries",
  "API design",
  "Microservices architecture",
  "Cybersecurity",
  "Penetration testing",
  "Browser automation",
  "Web scraping / crawling",
  "Data pipelines / ETL",
  "Game development",
  "Unity / Unreal",
  "AR / VR development",
  "Chrome extension development",
  "No-code / automation (Zapier, Make)",
  "Blockchain / smart contracts",
  "QA / test engineering",
  "Embedded / hardware engineering",
  // ── Design ───────────────────────────────────────────────────────────────
  "UI / UX design",
  "Product design",
  "Graphic design",
  "Branding / visual identity",
  "Logo design",
  "Illustration",
  "Motion / video design",
  "Design systems",
  "Figma / prototyping",
  "UX research",
  "Presentation design (pitch decks)",
  "Icon design",
  "Packaging design",
  "Print design",
  "Web design (conversion-focused)",
  "Color grading / photo editing",
  "Industrial design",
  "3D / CAD design",
  "Accessibility design",
  "Fashion design / styling",
  // ── Marketing ────────────────────────────────────────────────────────────
  "Digital marketing",
  "SEO / content marketing",
  "Social media marketing",
  "Email marketing",
  "Paid ads (Google / Meta)",
  "Growth / performance marketing",
  "Conversion rate optimization (CRO)",
  "Brand strategy",
  "Market positioning",
  "Go-to-market strategy",
  "Competitive intelligence",
  "PR / communications",
  "Influencer marketing",
  "Affiliate marketing",
  "Community-led growth",
  "LinkedIn marketing",
  "X (Twitter) marketing",
  "Reddit marketing",
  "YouTube / video marketing",
  "TikTok marketing",
  "Podcast marketing",
  "Event marketing",
  "Retargeting / remarketing",
  "Brand partnerships",
  // ── Sales ────────────────────────────────────────────────────────────────
  "Sales / closing deals",
  "B2B enterprise sales",
  "SDR / BDR (prospecting)",
  "Outbound / cold outreach",
  "Account management",
  "Business development",
  "Partnerships / channel sales",
  "Sales enablement",
  "CRM management (HubSpot, Salesforce)",
  "Pricing strategy",
  "Demo / product demos",
  "Negotiation",
  "Retail / in-person sales",
  "Inside sales",
  "Door-to-door / field sales",
  "Reseller / channel sales",
  "Term sheet negotiation",
  // ── Operations ───────────────────────────────────────────────────────────
  "Operations management",
  "Project management",
  "Supply chain / logistics",
  "Customer success",
  "Process improvement (Lean / Six Sigma)",
  "Event operations / coordination",
  "Vendor management",
  "Franchising / multi-location ops",
  "Warehouse / fulfillment operations",
  "Quality control / QA ops",
  "Production management",
  "Restaurant / kitchen management",
  "Healthcare operations",
  "Legal operations",
  "Fleet management",
  "Facility management",
  "Risk management",
  "Compliance operations",
  "Import / export / customs",
  // ── Data & Analytics ─────────────────────────────────────────────────────
  "Data analysis",
  "Business intelligence / dashboards",
  "Financial modeling",
  "Market research",
  "User research / UX research",
  "Statistics / quantitative analysis",
  "Excel / Google Sheets (power user)",
  "Tableau / Power BI",
  "Google Analytics / GA4",
  "A/B testing",
  "Product analytics (Mixpanel, Amplitude)",
  "Cohort analysis",
  "Predictive modeling",
  "Data visualization",
  "Web analytics",
  "Python / R for data analysis",
  // ── Content & Media ──────────────────────────────────────────────────────
  "Writing / copywriting",
  "Long-form writing / books",
  "Ghostwriting",
  "Email newsletters",
  "Blogging",
  "Technical writing / documentation",
  "Grant writing",
  "Press release writing",
  "Case study writing",
  "White paper writing",
  "Comedy writing",
  "Screenwriting / scriptwriting",
  "YouTube scripting",
  "Journalism / reporting",
  "Academic / research writing",
  "Video production / editing",
  "Podcast production",
  "Photography",
  "Short-form video (Reels, TikTok)",
  "Course creation / e-learning content",
  "Social media content",
  // ── Finance ──────────────────────────────────────────────────────────────
  "Financial analysis",
  "Accounting / bookkeeping",
  "Tax strategy (business)",
  "Fundraising / investor relations",
  "Startup fundraising (SAFEs, priced rounds)",
  "Private equity / M&A",
  "Personal finance / wealth management",
  "Trading / investing",
  "Crypto / DeFi trading",
  "Real estate finance",
  "Business valuation",
  "Cash flow management",
  "P&L management",
  "Payroll management",
  "Insurance",
  // ── Business & Strategy ───────────────────────────────────────────────────
  "Legal / contracts",
  "HR / recruiting",
  "Strategic planning",
  "Leadership / team management",
  "Customer support / CX",
  "Purchasing / procurement",
  "Pitch deck creation",
  "Business plan writing",
  "Franchise development",
  "International business",
  "IP / patent management",
  "Due diligence",
  "Benefits administration",
  "Executive assistant work",
  // ── Community & Education ─────────────────────────────────────────────────
  "Community management",
  "Discord server management",
  "Event planning",
  "Network building",
  "Coaching / mentorship",
  "Executive coaching",
  "Life coaching",
  "Career coaching",
  "College admissions consulting",
  "Public speaking",
  "Teaching / instruction",
  "Curriculum design",
  "Tutoring",
  "Sports coaching",
  "Online course delivery",
  "Workshop facilitation",
  "Podcast hosting",
  "YouTube channel growth",
  "Newsletter growth",
  // ── Healthcare & Trades ──────────────────────────────────────────────────
  "Healthcare / clinical",
  "Nursing",
  "EMT / paramedic",
  "Personal training / fitness coaching",
  "Nutrition / dietetics",
  "Mental health / therapy",
  "Physical therapy",
  "Pharmacy",
  "Dental hygiene",
  "Massage therapy",
  "Acupuncture",
  "Construction / contracting",
  "Electrical / plumbing",
  "HVAC",
  "Auto mechanics",
  "Landscaping / horticulture",
  "Cooking / culinary arts",
  "Catering",
  "Barbering / hair styling",
  "Tattoo artistry",
  "Pool service / maintenance",
  "Pest control",
  "Moving / delivery services",
];

export const COMMUNITY_OPTIONS = [
  // ── College & Campus ─────────────────────────────────────────────────────
  "College students / campus life",
  "Greek life (fraternities / sororities)",
  "Student athletes",
  "Graduate students / PhD researchers",
  "Pre-med / pre-law students",
  "International students",
  "HBCU communities",
  "Community college students",
  "MBA students / business school",
  "Law school students",
  "Medical school students",
  "College admissions prep communities",
  "Study abroad communities",
  // ── Sports & Recreation ──────────────────────────────────────────────────
  "Local sports leagues / intramurals",
  "Youth sports parents & coaches",
  "Golf players / country clubs",
  "Tennis / pickleball players",
  "Martial arts practitioners",
  "Runners / marathon community",
  "Cyclists / mountain bikers",
  "Rock climbers / bouldering",
  "Surfers / water sports",
  "Bowlers / bowling leagues",
  "Softball / kickball leagues",
  "Fantasy sports players",
  "Sports card / memorabilia collectors",
  "Competitive swimmers",
  "Track & field athletes",
  "Wrestling / grappling",
  "Boxing / kickboxing",
  "Powerlifters / Olympic weightlifters",
  "Obstacle course racers (Spartan / OCR)",
  "Triathletes",
  "Soccer / football players",
  "Basketball players",
  "Hockey players",
  "Lacrosse players",
  "Rugby players",
  "Ultimate frisbee",
  "Volleyball players",
  "Baseball / softball players",
  "Dance communities",
  "Cheerleading / gymnastics",
  "Equestrian / horseback riding",
  // ── Gaming & Esports ─────────────────────────────────────────────────────
  "Esports / competitive gaming",
  "Poker / card players",
  "Chess players",
  "Tabletop RPG (D&D, Pathfinder)",
  "Board game enthusiasts",
  "Video game speedrunners",
  "Twitch / streaming communities",
  "Console gaming (Xbox / PlayStation)",
  "PC gaming communities",
  "Roblox / Minecraft creators",
  "Mobile gaming communities",
  "Magic: The Gathering players",
  "Sports betting communities",
  "Drone pilots / FPV racing",
  // ── Fitness & Wellness ───────────────────────────────────────────────────
  "Gym regulars / weightlifters",
  "CrossFit communities",
  "Yoga / pilates practitioners",
  "Personal trainers / fitness coaches",
  "Nutrition / dietitian communities",
  "Running clubs",
  "Cycling clubs",
  "Sober communities",
  "Mental health / therapy communities",
  "Meditation / mindfulness communities",
  "Holistic health communities",
  // ── Tech & Developer ─────────────────────────────────────────────────────
  "Software developers / engineers",
  "Startup founders / indie hackers",
  "Freelance developers",
  "Open source contributors",
  "Game developers",
  "Web3 / crypto communities",
  "AI / ML practitioners",
  "DevOps / infrastructure engineers",
  "Mobile developers (iOS / Android)",
  "No-code / low-code builders",
  "Product managers",
  "UX / UI designers",
  "Data scientists / analysts",
  "Cybersecurity professionals",
  "Hackathon communities",
  "Prompt engineers / AI hobbyists",
  "Hacker News community",
  "Product Hunt community",
  "Solo SaaS founders",
  // ── Business & Professional ──────────────────────────────────────────────
  "Small business owners",
  "E-commerce sellers (Shopify / Amazon / Etsy)",
  "Freelancers / consultants",
  "Real estate agents / brokers",
  "Real estate investors (REI clubs)",
  "Financial advisors / planners",
  "Accountants / bookkeepers",
  "Lawyers / legal professionals",
  "Insurance agents",
  "Recruiters / HR professionals",
  "Marketing professionals",
  "Sales professionals",
  "Virtual assistants",
  "Executive assistants",
  "Business coaches",
  "Management consultants",
  "PR / communications professionals",
  "Notaries / document signers",
  "Mortgage brokers / loan officers",
  "Property managers",
  "Title agents / escrow officers",
  "Life coaches",
  "Career coaches",
  "Executive coaches",
  "Etsy shop owners",
  "Amazon FBA sellers",
  "Dropshippers / print-on-demand sellers",
  "eBay / resellers / flippers",
  "Domain investors / flippers",
  "Agency owners (digital marketing)",
  "Freelance copywriters",
  // ── Creative & Content ───────────────────────────────────────────────────
  "YouTubers / video creators",
  "Podcasters",
  "Streamers (Twitch / Kick)",
  "TikTok creators",
  "Instagram / social media influencers",
  "Bloggers / newsletter writers",
  "Substack writers",
  "Photographers",
  "Graphic designers",
  "Musicians / bands",
  "Artists / illustrators",
  "Filmmakers / video editors",
  "Animators",
  "Comic creators",
  "Voice actors",
  "Fashion designers / stylists",
  "Makeup artists",
  "Wedding planners",
  "Event photographers",
  "Music producers / beatmakers",
  "Session musicians",
  "Music teachers / private instructors",
  "Stand-up comedians",
  "Improv / theater communities",
  "Sound engineers",
  "DJ communities",
  "Acting / film communities",
  "Tattoo artists",
  // ── Trades & Labor ───────────────────────────────────────────────────────
  "Contractors / construction workers",
  "Electricians / plumbers",
  "HVAC technicians",
  "Auto mechanics",
  "Landscapers / lawn care",
  "Cleaning services / housekeeping",
  "Home staging / interior designers",
  "Welders / fabricators",
  "Roofers",
  "Painters / drywall workers",
  "Flooring / tile installers",
  "Solar installation workers",
  "Handymen / general contractors",
  // ── Food & Hospitality ───────────────────────────────────────────────────
  "Restaurant owners / managers",
  "Chefs / line cooks",
  "Bartenders",
  "Coffee shop / cafe owners",
  "Caterers / event food",
  "Food bloggers / reviewers",
  "Brewery / winery communities",
  "Food truck operators",
  "Personal chefs",
  "Bakers / pastry chefs",
  "Meal prep / meal kit communities",
  "Baristas",
  // ── Healthcare ───────────────────────────────────────────────────────────
  "Nurses / healthcare workers",
  "Therapists / counselors",
  "Dentists / dental professionals",
  "Veterinarians / vet techs",
  "Physical therapists / chiropractors",
  "Medical students / residents",
  "Pharmaceutical professionals",
  "Occupational therapists",
  "Midwives / doulas",
  "Acupuncturists",
  "Massage therapists",
  "EMTs / paramedics",
  "Geriatric care workers",
  "Addiction counselors",
  "First responders / firefighters",
  "Optometrists / ophthalmologists",
  "Dermatologists / aestheticians",
  // ── Education ────────────────────────────────────────────────────────────
  "K-12 teachers",
  "College professors / academics",
  "Tutors / test prep",
  "Homeschool parents",
  "School administrators",
  "Special education professionals",
  "Online course creators / educators",
  "Corporate trainers",
  "Language tutors",
  "College admissions consultants",
  "SAT / ACT tutors",
  "STEM educators",
  "Arts educators",
  "PE teachers / coaches",
  // ── Community & Social ───────────────────────────────────────────────────
  "Local neighborhood communities",
  "Church / religious communities",
  "Veterans / military communities",
  "Military spouses",
  "Parents of young children",
  "Parents of teens / student athletes",
  "Expats / digital nomads",
  "LGBTQ+ communities",
  "Non-profit workers",
  "Political organizers / activists",
  "Book clubs",
  "Hiking / outdoor communities",
  "Pet owners (dogs, cats)",
  "Car enthusiasts / gearheads",
  "Vintage / thrift collectors",
  "Sneaker collectors",
  "Watch enthusiasts",
  "Audiophile communities",
  "Film photography / analog communities",
  "Vinyl record collectors",
  "Whiskey / spirits enthusiasts",
  "Wine enthusiasts",
  "Craft cocktail community",
  "Coffee enthusiasts",
  "Overlanding / off-road communities",
  "Van life / RV communities",
  "Homesteaders / self-sufficiency",
  "Hunters / fishermen",
  "Fly fishing community",
  "Archery / shooting sports",
  "Beekeepers",
  "Urban farmers / gardeners",
  "Ham radio operators",
  "Preppers / survivalists",
  "Camping / bushcraft communities",
  "Craft / DIY communities",
  "Knitting / crochet communities",
  // ── Finance & Investing ──────────────────────────────────────────────────
  "Day traders / stock investors",
  "Crypto investors / traders",
  "Personal finance enthusiasts (FIRE)",
  "Angel investors / VCs",
  "Real estate investors (flippers)",
  "Options traders",
  "Sports bettors",
  "NFT / digital asset collectors",
  // ── Parent & Family ──────────────────────────────────────────────────────
  "New parents / new moms",
  "Single parents",
  "Empty nesters",
  "Caretakers of elderly parents",
  "Families with special needs children",
  "Adoptive / foster parents",
  // ── Identity & Life Stage ─────────────────────────────────────────────────
  "Recent college grads",
  "Gap year students",
  "Career changers",
  "Recently divorced / separated",
  "Retirees / seniors",
  "Immigrants / first-gen Americans",
  "Black / African-American communities",
  "Latinx communities",
  "Asian-American communities",
  "South Asian communities",
  "Middle Eastern communities",
  "Native American communities",
  "Rural communities",
  // ── Age & Generation ─────────────────────────────────────────────────────
  "Teenagers (13-17)",
  "College-age adults (18-24)",
  "Gen Z (born 1997-2012)",
  "Millennials (born 1981-1996)",
  "Gen X (born 1965-1980)",
  "Boomers (born 1946-1964)",
  "Seniors 65+",
  // ── Gender & Identity ────────────────────────────────────────────────────
  "Women in tech",
  "Women founders / female entrepreneurs",
  "Women in business",
  "Dads / fatherhood communities",
  "LGBTQ+ founders / entrepreneurs",
  // ── Crafts & Making ──────────────────────────────────────────────────────
  "Sewing / quilting",
  "Pottery / ceramics",
  "Woodworking / woodcraft",
  "Embroidery / needlepoint",
  "Candle making / soap making",
  "Jewelry making / metalsmithing",
  "Leather working",
  "Scrapbooking / paper crafts",
  "3D printing enthusiasts",
  "DIY electronics / Arduino / Raspberry Pi",
  "Model building / scale models",
  "Cosplay / prop making",
  "Resin art",
  "Macrame / fiber arts",
  "Painting / watercolor / oil painting",
  "Screen printing / printmaking",
];

export const TECH_OPTIONS = [
  "Little to none",
  "Just getting started",
  "Can build basic apps",
  "Strong developer",
  "Full-stack / senior engineer",
];

export const GOAL_OPTIONS = [
  "Fun side project",
  "Profitable side project",
  "Bootstrapped small business",
  "Funded startup",
  "Building a full company",
  "Still figuring it out",
];

export const MONETIZATION_OPTIONS = [
  "Subscriptions (recurring)",
  "One-time purchase",
  "Free + paid tier (freemium)",
  "Whatever makes most sense",
  "Not sure yet",
];

export const COMMUNITY_SET = new Set(COMMUNITY_OPTIONS);

export const BUILD_TYPE_OPTIONS = [
  "Software / app",
  "Service business",
  "Physical product",
  "Content / media",
  "Not sure yet",
];
