import type { Opportunity } from "./types";

export const INITIAL_DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-001",
    title: "AI Security Questionnaire Assistant",
    description: "Automates repetitive enterprise security review and vendor assessment questionnaires (SOC 2, ISO 27001, SIG).",
    problem: "B2B SaaS companies spend 20-40 hours per deal manually answering 300+ question security spreadsheets, delaying sales cycles by weeks.",
    targetCustomer: "B2B SaaS companies ($1M-$30M ARR) selling to mid-market and enterprise accounts",
    industry: "Cybersecurity",
    currentWorkflow: "Sales engineers and InfoSec leads manually copy answers between past spreadsheets, Notion compliance docs, and email threads.",
    currentSolutions: "Legacy procurement suites (Loopio, Whistic) priced at $25K+/yr with rigid clunky search, or manual spreadsheet slog.",
    whyInteresting: "Direct sales velocity blocker with clear economic ROI ($10K+ saved per closed deal) and immediate willingness to pay.",
    whyTheProblemMatters: "Deals get stuck in late-stage procurement. Shortening security review time from 3 weeks to 2 hours directly accelerates revenue.",
    economicImpact: "Estimated 25 engineering/sales hours saved per enterprise deal, reducing deal cycle by 14 days.",
    marketSize: "Over 45,000 B2B SaaS companies globally subject to enterprise vendor risk management.",
    marketGap: "Existing tools are built for procurement buyers, not for vendors who just want an accurate, instant answer auto-filler with citation links to policies.",
    aiOpportunity: "Vector embeddings over company compliance docs, SOC 2 reports, and previous questionnaires with verified reference citations.",
    aiFit: "HIGH",
    aiPriority: "HIGH_POTENTIAL",
    aiPriorityReasons: [
      "recurring high-urgency pain point",
      "strong evidence across sales communities",
      "measurable economic cost in delayed deals",
      "existing willingness to pay documented",
      "ideal semantic retrieval AI fit",
      "underserved vendor-side pricing gap",
    ],
    aiConfidence: "HIGH",
    researchScore: 88,
    researchScoreFactors: {
      problemSeverity: 9,
      problemFrequency: 9,
      economicValue: 9,
      willingnessToPay: 9,
      marketOpportunity: 8,
      competitionGap: 8,
      aiFit: 10,
      technicalFeasibility: 9,
      distributionPotential: 8,
      evidenceStrength: 9,
    },
    evidenceStrength: "HIGH",
    myDecision: "INTERESTED",
    nextAction: "Interview 5 B2B SaaS Sales Engineers about questionnaire turnaround times",
    myThoughts: "This is a fantastic painkiller. We could start with a Chrome extension and Excel plugin that indexes security policies and autofills web portals like Whistic/OneTrust.",
    mvpFeatures: [
      "Upload SOC 2 report, privacy policy, and past questionnaires (PDF/Excel)",
      "Chrome extension to auto-detect question fields in web portals",
      "Confidence score per answer with source policy snippet citation",
      "Export back to original Excel/CSV format",
    ],
    excludedFeatures: ["Full compliance certification audit", "Vendor risk scoring of third parties"],
    monetizationModel: "B2B Subscription",
    pricingIdea: "$299/month for up to 10 questionnaires/month; $799/month unlimited",
    distributionChannels: ["Sales engineering communities (Presales Collective)", "Outbound to Heads of InfoSec", "Product Hunt launch"],
    executionRisks: [
      { risk: "Hallucinated answers causing security liability", mitigation: "Strict citation requirement with human-in-the-loop review toggle" },
    ],
    validation: {
      interviewsCount: 4,
      interestedCustomersCount: 3,
      waitlistCount: 18,
      landingPageResults: "28% conversion on headline: 'Answer security questionnaires in 5 minutes'",
      pricingExperiments: "Tested $199 vs $499/mo; 3 sales engineers confirmed $499 is an easy corporate card expense",
      feedback: "Must support multi-tab Excel files and OneTrust web portals",
      assumptions: [
        "Founders will trust AI with their SOC 2 confidential report",
        "Chrome extension can reliably inject into custom web portal forms",
      ],
      risks: ["Liability if an answer misrepresents security posture"],
      validationQuestions: ["How many questionnaires do you receive each month?", "Who currently fills them out?"],
    },
    competitors: [
      { name: "Loopio", url: "https://loopio.com", pricing: "$15,000-$30,000/yr", strengths: ["Enterprise market share", "RFP management"], weaknesses: ["Clunky legacy UX", "Huge upfront sales contract"] },
      { name: "Whistic", url: "https://whistic.com", pricing: "$20,000/yr", strengths: ["Network of verified profiles"], weaknesses: ["Buyer-focused, slow vendor workflow"] },
    ],
    sources: [
      {
        id: "src-001",
        title: "Reddit r/salesengineering: How much time do you waste on security questionnaires?",
        url: "https://reddit.com/r/salesengineering/comments/example1",
        sourceType: "reddit",
        date: "2026-08-14",
        summary: "Over 80 comments agreeing that security questionnaires are the single most hated task for SEs, taking 15+ hours weekly.",
        evidenceRelevance: "Validates extreme frustration and high frequency.",
        grading: "SOURCE_BASED_CLAIM",
      },
      {
        id: "src-002",
        title: "Hacker News: Ask HN: Tools to automate SOC2 questionnaires?",
        url: "https://news.ycombinator.com/item?id=example2",
        sourceType: "hackernews",
        date: "2026-07-22",
        summary: "Founders asking for self-serve affordable alternatives to Loopio and RFPio.",
        evidenceRelevance: "Demonstrates active organic search demand.",
        grading: "FACT",
      },
    ],
    notes: [
      {
        id: "note-001",
        content: "Spoke with Alex (SE Director at series B SaaS). Confirmed they have 1 full-time person doing nothing but filling out questionnaires.",
        createdAt: "2026-09-10T14:22:00Z",
      },
    ],
    status: "DEEP_RESEARCH",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: true,
    saved: true,
    tags: ["Cybersecurity", "SalesOps", "B2B", "Compliance"],
    createdAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-15T16:30:00Z",
  },
  {
    id: "opp-002",
    title: "Autonomous Multi-Entity Reconciliation Engine",
    description: "Automated intercompany ledger reconciliation and currency fluctuation balancing for international subsidiaries.",
    problem: "Finance teams manually match bank transactions, Stripe payouts, and ERP entries across multiple global entities every month-end close.",
    targetCustomer: "CFOs, VP Finance, and controllers at venture-backed multi-entity businesses ($5M-$50M ARR)",
    industry: "Finance",
    currentWorkflow: "Accountants spend 4 days every month downloading CSVs and manually cross-matching transaction IDs in Excel spreadsheets.",
    currentSolutions: "BlackLine (enterprise only, $50K+) or general ERP modules like NetSuite which don't handle intercompany cross-clearing smoothly.",
    whyInteresting: "High willingness to pay, severe month-end closing crunch, quantifiable reduction in outsourced accounting fees.",
    whyTheProblemMatters: "Delays financial reporting to investors and board, creates audit exposure, and burns out finance team members.",
    economicImpact: "Reduces month-end close by 3 full working days per month.",
    marketSize: "Over 20,000 multi-entity tech companies with global distributed operations.",
    marketGap: "Mid-market gap between basic QuickBooks (no multi-entity support) and massive enterprise BlackLine implementations.",
    aiOpportunity: "Intelligent fuzzy matching of fragmented bank narration strings, multi-currency conversions, and tax reconciliation.",
    aiFit: "HIGH",
    aiPriority: "HIGH_POTENTIAL",
    aiPriorityReasons: [
      "severe recurring month-end pain",
      "high willingness to pay from corporate finance budgets",
      "strong economic ROI in billable accountant hours",
      "clear market gap between SMB and enterprise ERP",
    ],
    aiConfidence: "HIGH",
    researchScore: 84,
    researchScoreFactors: {
      problemSeverity: 9,
      problemFrequency: 8,
      economicValue: 9,
      willingnessToPay: 9,
      marketOpportunity: 8,
      competitionGap: 7,
      aiFit: 8,
      technicalFeasibility: 8,
      distributionPotential: 9,
      evidenceStrength: 9,
    },
    evidenceStrength: "HIGH",
    myDecision: "INTERESTED",
    nextAction: "Contact 3 outsourced CFO agencies to test willingness to pay $499/mo",
    myThoughts: "Selling through fractional CFO firms could be the ultimate distribution wedge because they handle 10-20 client ledgers each.",
    mvpFeatures: [
      "Plaid & Stripe multi-currency bank feed integration",
      "Rules-based + AI fuzzy reconciliation matching",
      "Audit trail log with one-click discrepancy resolution",
    ],
    validation: {
      interviewsCount: 3,
      interestedCustomersCount: 2,
      waitlistCount: 12,
      assumptions: ["Fractional CFOs are willing to mandate clients to use our tool"],
      risks: ["Strict SOC 1 / SOC 2 Type II expectations from finance buyers"],
      validationQuestions: ["How long does intercompany reconciliation take each month?"],
    },
    competitors: [
      { name: "BlackLine", url: "https://blackline.com", pricing: "$40,000+/yr", strengths: ["Fortune 500 standard"], weaknesses: ["Prohibitively complex for <$50M ARR"] },
    ],
    sources: [
      {
        id: "src-003",
        title: "CFO Connect Survey on Month-End Bottlenecks",
        url: "https://cfoconnect.com/resources/close-survey",
        sourceType: "web",
        summary: "67% of CFOs cite intercompany reconciliation and FX adjustments as primary cause of close delays.",
        grading: "FACT",
      },
    ],
    notes: [],
    status: "REVIEW",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: true,
    tags: ["Finance", "Fintech", "B2B", "Accounting"],
    createdAt: "2026-09-09T11:15:00Z",
    updatedAt: "2026-09-14T18:00:00Z",
  },
  {
    id: "opp-003",
    title: "Automated Medical Provider Credentialing & Payer Enrollment",
    description: "Streamlines CAQH updates, state medical license verification, and commercial health insurance panel onboarding for clinics.",
    problem: "Clinics lose $8,000 to $15,000 per doctor per month in unbillable revenue while waiting 90-120 days for manual payer enrollment.",
    targetCustomer: "Private practices, dental groups, and digital health clinics (10-100 practitioners)",
    industry: "Healthcare",
    currentWorkflow: "Practice managers manually fill out 50-page paper/PDF applications for every insurance payer (Aetna, BCBS, United, Cigna).",
    currentSolutions: "Outsourced credentialing agencies charging $1,500/provider or legacy hospital software like symplr.",
    whyInteresting: "Direct unbillable revenue hemorrhage makes ROI unquestionable. Any tool that shaves 30 days off credentialing is an instant buy.",
    whyTheProblemMatters: "Doctors cannot treat patients under in-network insurance until payer enrollment clears, leaving clinics with idle staff.",
    economicImpact: "Shaving 30 days of credentialing delay restores ~$10,000 in clinical billing per physician.",
    marketSize: "Over 230,000 ambulatory clinics and medical practices in the United States.",
    marketGap: "Digital health clinics and expanding specialty practices are ignored by slow legacy enterprise credentialing software.",
    aiOpportunity: "Automated OCR extraction from provider CVs and automated form pre-filling across disparate payer portals.",
    aiFit: "HIGH",
    aiPriority: "HIGH_POTENTIAL",
    aiPriorityReasons: [
      "massive direct revenue loss per day of delay",
      "universal administrative regulatory bottleneck",
      "very high willingness to pay",
      "low customer price sensitivity",
    ],
    aiConfidence: "HIGH",
    researchScore: 82,
    researchScoreFactors: {
      problemSeverity: 10,
      problemFrequency: 7,
      economicValue: 10,
      willingnessToPay: 9,
      marketOpportunity: 8,
      competitionGap: 7,
      aiFit: 7,
      technicalFeasibility: 7,
      distributionPotential: 8,
      evidenceStrength: 9,
    },
    evidenceStrength: "HIGH",
    myDecision: "SHORTLISTED",
    nextAction: "Build prototype scraper for NPI and state medical board licensing APIs",
    myThoughts: "The revenue leakage is so painful that practice managers will gladly pay $150/provider/month.",
    mvpFeatures: [
      "Automated NPI and state license status verification",
      "Single provider profile sync to CAQH ProView",
      "Payer enrollment packet auto-generation",
    ],
    validation: {
      interviewsCount: 5,
      interestedCustomersCount: 4,
      waitlistCount: 22,
      assumptions: ["Clinics can grant delegate access to their CAQH accounts"],
      risks: ["Payer portals changing form formats without notice"],
      validationQuestions: ["What is your average turnaround time for new commercial payer panels?"],
    },
    competitors: [
      { name: "Medallion", url: "https://medallion.co", pricing: "Custom enterprise", strengths: ["Strong VC backing"], weaknesses: ["Expensive, focused on massive digital health"] },
    ],
    sources: [
      {
        id: "src-004",
        title: "MGMA Stat Poll: Credentialing Delays Impacting Practice Cash Flow",
        url: "https://mgma.com/stat-poll-credentialing",
        sourceType: "web",
        summary: "78% of practices report credentialing delays directly impacting revenue collection.",
        grading: "FACT",
      },
    ],
    notes: [],
    status: "SHORTLIST",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: true,
    saved: true,
    tags: ["Healthcare", "HealthTech", "B2B", "Compliance"],
    createdAt: "2026-09-07T09:30:00Z",
    updatedAt: "2026-09-16T12:00:00Z",
  },
  {
    id: "opp-004",
    title: "Ephemeral PR Staging Environments on Kubernetes",
    description: "Spin up lightweight, isolated pull-request preview environments with sanitized database clones on every Git commit.",
    problem: "Shared staging environments are constantly broken, bottlenecking QA and product managers, while current preview tools are over-engineered.",
    targetCustomer: "Engineering teams of 15-80 developers running microservices on Kubernetes",
    industry: "Developer Tools",
    currentWorkflow: "Developers wait in line for 'staging' or merge untested branches that break internal testing for everyone else.",
    currentSolutions: "Bunnyshell, Shipyard, Release.com, or bespoke internal DevOps scripts that constantly break.",
    whyInteresting: "High developer pain, fast iteration cycles, but crowded space with high cloud infrastructure costs.",
    aiFit: "MEDIUM",
    aiPriority: "MEDIUM_POTENTIAL",
    aiPriorityReasons: [
      "clear developer friction",
      "well-understood technical architecture",
      "crowded competitive space",
      "high churn if cloud bills spike",
    ],
    aiConfidence: "HIGH",
    researchScore: 74,
    researchScoreFactors: {
      problemSeverity: 8,
      problemFrequency: 9,
      economicValue: 7,
      willingnessToPay: 7,
      marketOpportunity: 7,
      competitionGap: 6,
      aiFit: 7,
      technicalFeasibility: 8,
      distributionPotential: 7,
      evidenceStrength: 8,
    },
    evidenceStrength: "MEDIUM",
    myDecision: "UNDECIDED",
    nextAction: "Research competitor pricing models (Bunnyshell, Uffizzi, Shipyard)",
    myThoughts: "Infrastructure margins can be tough unless we bring-your-own-cloud (BYOC) directly into customer AWS/GCP accounts.",
    validation: {
      interviewsCount: 2,
      interestedCustomersCount: 1,
      waitlistCount: 8,
      assumptions: ["Teams have Kubernetes clusters they are willing to grant access to"],
      risks: ["High compute resource consumption leading to unexpected cloud bills"],
      validationQuestions: ["How do your product managers currently review PRs before merging?"],
    },
    competitors: [
      { name: "Bunnyshell", url: "https://bunnyshell.com", pricing: "$49-$499/mo", strengths: ["Feature rich"], weaknesses: ["Complex setup"] },
    ],
    sources: [],
    notes: [],
    status: "REVIEW",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: false,
    tags: ["DevTools", "Kubernetes", "DevOps", "CI/CD"],
    createdAt: "2026-09-10T14:00:00Z",
    updatedAt: "2026-09-12T16:00:00Z",
  },
  {
    id: "opp-005",
    title: "Commercial Lease Abstraction & Rent Escalation Auditor",
    description: "Scans 80-page commercial lease agreements to automatically extract rent escalation clauses, CAM fees, and renewal deadlines into calendar alerts.",
    problem: "Commercial property managers miss indexation escalations and renewal notification windows, forfeiting 2-5% of annual Net Operating Income.",
    targetCustomer: "Commercial property managers and real estate family offices managing 10-100 buildings",
    industry: "Real Estate",
    currentWorkflow: "Paralegals manually read 100-page leases and type numbers into outdated Yardi or MRI software.",
    currentSolutions: "Outsourced legal service providers in India charging $250-$500 per lease abstraction.",
    whyInteresting: "Clear ROI directly tied to property Net Operating Income; sweet spot for OCR + LLM vision models.",
    aiFit: "HIGH",
    aiPriority: "MEDIUM_POTENTIAL",
    aiPriorityReasons: [
      "clear ROI tied to net operating income",
      "unstructured legal PDF parsing fits LLMs perfectly",
      "traditional real estate buyers have long sales cycles",
    ],
    aiConfidence: "MEDIUM",
    researchScore: 71,
    researchScoreFactors: {
      problemSeverity: 7,
      problemFrequency: 6,
      economicValue: 8,
      willingnessToPay: 8,
      marketOpportunity: 7,
      competitionGap: 7,
      aiFit: 9,
      technicalFeasibility: 8,
      distributionPotential: 5,
      evidenceStrength: 6,
    },
    evidenceStrength: "MEDIUM",
    myDecision: "UNDECIDED",
    nextAction: "Review 3 redacted commercial leases to test LLM extraction accuracy",
    myThoughts: "Commercial real estate buyers are slow to adopt new software, but if we partner with boutique property management firms, we could get early traction.",
    validation: {
      interviewsCount: 1,
      interestedCustomersCount: 1,
      waitlistCount: 4,
      assumptions: ["Managers will trust automated extraction without hiring human lawyers"],
      risks: ["Missing a complex rent escalation subclause"],
      validationQuestions: ["How do you currently track CPI rent increases across retail tenants?"],
    },
    competitors: [],
    sources: [],
    notes: [],
    status: "NEW",
    isUserGenerated: true,
    createdBy: "USER",
    source: "Manual",
    favorite: false,
    saved: true,
    tags: ["Real Estate", "PropTech", "LegalTech", "B2B"],
    createdAt: "2026-09-14T08:00:00Z",
    updatedAt: "2026-09-14T08:00:00Z",
  },
  {
    id: "opp-006",
    title: "Async Technical Code Screening & Take-Home Evaluator",
    description: "Evaluates candidates' real-world Git pull requests with consistent automated rubric scoring, anti-plagiarism checks, and feedback drafting.",
    problem: "Senior engineers spend 5+ hours weekly reviewing mediocre take-home code tests, leading to burnout and slow hiring loops.",
    targetCustomer: "Fast-growing tech startups (50-300 employees) hiring remote developers",
    industry: "Recruiting",
    currentWorkflow: "Engineers clone GitHub repos, try to compile locally, and manually write review notes in Google Docs.",
    currentSolutions: "HackerRank/LeetCode (algorithmic trivia candidates hate) or manual review.",
    whyInteresting: "Saves high-cost senior engineering time; improves candidate turnaround from 7 days to 2 hours.",
    aiFit: "HIGH",
    aiPriority: "MEDIUM_POTENTIAL",
    aiPriorityReasons: [
      "senior engineer time is extremely expensive",
      "hiring speed is a competitive edge",
      "some engineering skepticism toward AI grading fairness",
    ],
    aiConfidence: "MEDIUM",
    researchScore: 68,
    researchScoreFactors: {
      problemSeverity: 7,
      problemFrequency: 8,
      economicValue: 7,
      willingnessToPay: 6,
      marketOpportunity: 7,
      competitionGap: 6,
      aiFit: 8,
      technicalFeasibility: 8,
      distributionPotential: 6,
      evidenceStrength: 5,
    },
    evidenceStrength: "MEDIUM",
    myDecision: "INTERESTED",
    nextAction: "Run Reddit validation poll on r/experienceddevs about AI take-home grading",
    myThoughts: "Must be transparent with candidate feedback and focus on code architecture, test coverage, and documentation.",
    validation: {
      interviewsCount: 2,
      interestedCustomersCount: 1,
      waitlistCount: 9,
      assumptions: ["Candidates won't revolt if an AI assists in grading their take-home"],
      risks: ["Biased rubric penalties for unconventional architectural styles"],
      validationQuestions: ["How many take-home assignments do your engineers review each week?"],
    },
    competitors: [],
    sources: [],
    notes: [],
    status: "REVIEW",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: false,
    tags: ["Recruiting", "HRTech", "DevTools"],
    createdAt: "2026-09-11T12:00:00Z",
    updatedAt: "2026-09-13T10:00:00Z",
  },
  {
    id: "opp-007",
    title: "SOP Drift Detector & Compliance Automation",
    description: "Monitors Loom videos, Slack messages, and Jira updates to detect when operational teams deviate from documented standard operating procedures.",
    problem: "Scaling operations teams experience 30%+ error rates because onboarding documentation goes stale within weeks of creation.",
    targetCustomer: "COOs and Ops Managers at logistics, fintech, and marketplace startups (50-200 ops agents)",
    industry: "Operations",
    currentWorkflow: "Notion and Google Docs SOPs stay unread; managers manually audit random tickets once a month.",
    currentSolutions: "Trainual or Scribe (good for authoring, but zero passive monitoring of compliance or drift).",
    whyInteresting: "Solves the 'knowledge base cemetery' problem where nobody reads documentation after day 1.",
    aiFit: "HIGH",
    aiPriority: "MEDIUM_POTENTIAL",
    aiPriorityReasons: [
      "pervasive documentation rot in growing companies",
      "continuous ambient analysis is only possible with modern LLMs",
      "internal operational change management can be slow",
    ],
    aiConfidence: "MEDIUM",
    researchScore: 65,
    researchScoreFactors: {
      problemSeverity: 7,
      problemFrequency: 8,
      economicValue: 6,
      willingnessToPay: 6,
      marketOpportunity: 7,
      competitionGap: 7,
      aiFit: 8,
      technicalFeasibility: 6,
      distributionPotential: 5,
      evidenceStrength: 5,
    },
    evidenceStrength: "MEDIUM",
    myDecision: "SHORTLISTED",
    nextAction: "Build Slack bot prototype to capture process question snippets",
    myThoughts: "Every ops manager complains about answering the same 5 questions every week. This can auto-flag missing SOP sections.",
    validation: {
      interviewsCount: 3,
      interestedCustomersCount: 2,
      waitlistCount: 14,
      assumptions: ["Teams will install a bot with read access to operational Slack channels"],
      risks: ["Noise and false alarms annoying operators"],
      validationQuestions: ["How do you know when an employee follows an outdated procedure?"],
    },
    competitors: [],
    sources: [],
    notes: [],
    status: "SHORTLIST",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: true,
    tags: ["Operations", "OpsTech", "KnowledgeManagement"],
    createdAt: "2026-09-06T15:00:00Z",
    updatedAt: "2026-09-15T11:00:00Z",
  },
  {
    id: "opp-008",
    title: "Cross-Border Sales Tax & Nexus Threshold Monitor",
    description: "Real-time tracking of economic nexus thresholds across all 50 US states and EU VAT rules for digital product sellers.",
    problem: "SaaS founders inadvertently trigger sales tax nexus in multiple states without realizing compliance obligations until penalized.",
    targetCustomer: "Bootstrapped software and digital product creators ($100K-$1M ARR)",
    industry: "Accounting",
    currentWorkflow: "Founders ignore sales tax until an acquisition or until receiving a state tax audit demand letter.",
    currentSolutions: "Stripe Tax, Anrok, and TaxJar.",
    whyInteresting: "Real fear of audit penalties, but incumbents already offer automated solutions integrated into checkout.",
    aiFit: "MEDIUM",
    aiPriority: "LOW_POTENTIAL",
    aiPriorityReasons: [
      "entrenched incumbents like Stripe Tax and Anrok",
      "low switching incentive from existing billing stack",
      "high legal liability for tax miscalculations",
    ],
    aiConfidence: "HIGH",
    researchScore: 52,
    researchScoreFactors: {
      problemSeverity: 7,
      problemFrequency: 4,
      economicValue: 5,
      willingnessToPay: 5,
      marketOpportunity: 6,
      competitionGap: 3,
      aiFit: 5,
      technicalFeasibility: 6,
      distributionPotential: 6,
      evidenceStrength: 5,
    },
    evidenceStrength: "MEDIUM",
    myDecision: "REJECTED",
    nextAction: "Compare API pricing of Stripe Tax vs standalone nexus calculators",
    myThoughts: "Too crowded and defenseless. Stripe Tax and Paddle already solve this natively at the merchant of record level.",
    validation: {
      interviewsCount: 2,
      interestedCustomersCount: 0,
      waitlistCount: 2,
      assumptions: ["SaaS founders want a third-party tax tool separate from Stripe"],
      risks: ["Stripe Tax adding the exact missing feature for free"],
      validationQuestions: ["Do you use Stripe Tax or Paddle for nexus tracking?"],
    },
    competitors: [
      { name: "Stripe Tax", url: "https://stripe.com/tax", pricing: "0.5% per transaction", strengths: ["Built directly into checkout"], weaknesses: ["Doesn't file tax returns for you"] },
      { name: "Anrok", url: "https://anrok.com", pricing: "Custom", strengths: ["Purpose built for SaaS"], weaknesses: ["Expensive for early stage"] },
    ],
    sources: [],
    notes: [],
    status: "NEW",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: false,
    tags: ["Accounting", "Tax", "SaaS", "Compliance"],
    createdAt: "2026-09-12T10:00:00Z",
    updatedAt: "2026-09-12T10:00:00Z",
  },
  {
    id: "opp-009",
    title: "B2B Competitor Ad Spend & Messaging Radar",
    description: "Scrapes LinkedIn Ads Library and Google Ads Transparency Center to notify marketing teams when competitors test new hooks and positioning.",
    problem: "Product marketers manually inspect ad libraries once a quarter, missing timely insights into rival campaigns and target personas.",
    targetCustomer: "B2B Demand Gen and Product Marketing managers at growth-stage SaaS",
    industry: "Marketing",
    currentWorkflow: "Marketers set calendar reminders to manually check LinkedIn Ad Library for 10 competitor company pages.",
    currentSolutions: "AdSpy tools focused heavily on e-commerce Facebook/TikTok dropshipping ads rather than B2B enterprise LinkedIn ads.",
    whyInteresting: "Interesting vanity metric, but low urgency and high churn rate.",
    aiFit: "MEDIUM",
    aiPriority: "LOW_POTENTIAL",
    aiPriorityReasons: [
      "nice-to-have vitamin product rather than painkiller",
      "ad libraries have aggressive scraping protections and captcha barriers",
      "notoriously high customer churn in marketing intelligence tools",
    ],
    aiConfidence: "HIGH",
    researchScore: 48,
    researchScoreFactors: {
      problemSeverity: 5,
      problemFrequency: 6,
      economicValue: 4,
      willingnessToPay: 4,
      marketOpportunity: 6,
      competitionGap: 4,
      aiFit: 6,
      technicalFeasibility: 7,
      distributionPotential: 6,
      evidenceStrength: 4,
    },
    evidenceStrength: "LOW",
    myDecision: "REJECTED",
    nextAction: "Interview 3 demand gen marketers on monthly tooling budget",
    myThoughts: "Feels like a cool Twitter/X demo that people favorite but nobody pays $99/month for after month 2.",
    validation: {
      interviewsCount: 3,
      interestedCustomersCount: 1,
      waitlistCount: 5,
      assumptions: ["Marketers will act on competitor ad copy notifications"],
      risks: ["LinkedIn blocking scrapers causing high proxy costs"],
      validationQuestions: ["How often do you change your marketing strategy based on competitor ads?"],
    },
    competitors: [],
    sources: [],
    notes: [],
    status: "REVIEW",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: false,
    tags: ["Marketing", "AdTech", "CompetitiveIntelligence"],
    createdAt: "2026-09-13T16:00:00Z",
    updatedAt: "2026-09-13T16:00:00Z",
  },
  {
    id: "opp-010",
    title: "Return Fraud & Serial Wardrobing Predictor",
    description: "Flags checkout customers with high historical probability of buying clothing items solely for social media photos and returning them damaged.",
    problem: "Apparel merchants lose 15-20% of merchandise value on fraudulent returns, but blocking legitimate buyers tanks conversion.",
    targetCustomer: "Shopify Plus fashion and luxury goods merchants",
    industry: "E-commerce",
    currentWorkflow: "Warehouse staff manually inspect returned clothing for perfume odors, removed tags, or makeup stains.",
    currentSolutions: "Signifyd, Forter, or basic Shopify fraud risk indicators.",
    whyInteresting: "Huge dollar value problem, but requires cross-merchant data network effects that a solo founder cannot easily build.",
    aiFit: "MEDIUM",
    aiPriority: "VERY_LOW_PRIORITY",
    aiPriorityReasons: [
      "requires massive cross-merchant data network effects to be accurate",
      "severe cold start data problem for new software",
      "privacy regulations (GDPR/CCPA) restrict merchant customer blacklists",
      "established anti-fraud giants dominate the checkout space",
    ],
    aiConfidence: "HIGH",
    researchScore: 36,
    researchScoreFactors: {
      problemSeverity: 6,
      problemFrequency: 4,
      economicValue: 4,
      willingnessToPay: 4,
      marketOpportunity: 4,
      competitionGap: 2,
      aiFit: 4,
      technicalFeasibility: 4,
      distributionPotential: 2,
      evidenceStrength: 4,
    },
    evidenceStrength: "LOW",
    myDecision: "REJECTED",
    nextAction: "Archive findings and benchmark against Shopify Flow scripts",
    myThoughts: "Network effect moats make this impossible for a startup without existing e-commerce consortium data.",
    validation: {
      interviewsCount: 1,
      interestedCustomersCount: 0,
      waitlistCount: 0,
      assumptions: ["Merchants will share return data across competitors"],
      risks: ["False positives alienating VIP customers"],
      validationQuestions: ["What percentage of returns do you write off as unsellable?"],
    },
    competitors: [
      { name: "Signifyd", url: "https://signifyd.com", pricing: "Custom percentage of GMV", strengths: ["Enormous shared commerce network"], weaknesses: ["Enterprise only"] },
    ],
    sources: [],
    notes: [],
    status: "REJECTED",
    isUserGenerated: false,
    createdBy: "AI",
    source: "Hermes",
    favorite: false,
    saved: false,
    tags: ["Ecommerce", "Fraud", "RetailTech"],
    createdAt: "2026-09-05T12:00:00Z",
    updatedAt: "2026-09-14T09:00:00Z",
  },
];
