import { db } from "@/lib/db";
import { telegramMessagesTable } from "@/lib/db/schema";
import { getIntegrationCredentials } from "@/lib/integrations/vault";
import type { Opportunity } from "@/lib/opportunities/types";

export interface TelegramDispatchResult {
  success: boolean;
  messageId?: string;
  error?: string;
  previewText: string;
}

/**
 * Formats a list of opportunities into a clean, concise Telegram digest
 */
export function formatTelegramDigest(opportunities: Opportunity[]): string {
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  let text = `🚀 *SaaS Opportunity Radar Digest*\n`;
  text += `📅 ${dateStr} • ${opportunities.length} Curated Opportunities\n\n`;

  opportunities.forEach((opp, index) => {
    text += `*${index + 1}. ${opp.title}*\n`;
    text += `⭐ *Score*: ${opp.researchScore}/100 | *Priority*: ${opp.aiPriority.replace("_", " ")}\n`;
    text += `🎯 *Target*: ${opp.targetCustomer}\n`;
    text += `⚠️ *Problem*: ${opp.problem.slice(0, 180)}${opp.problem.length > 180 ? "..." : ""}\n`;
    if (opp.aiOpportunity) {
      text += `💡 *AI Fit*: ${opp.aiOpportunity.slice(0, 140)}...\n`;
    }
    if (opp.pricingIdea || opp.monetizationModel) {
      text += `💰 *Pricing*: ${opp.pricingIdea || opp.monetizationModel}\n`;
    }
    text += `🔗 http://localhost:3000?selected=${opp.id}\n\n`;
  });

  text += `_Generated by Local-First SaaS Opportunity Radar_`;
  return text;
}

/**
 * Sends formatted opportunities digest to Telegram bot chat
 */
export async function sendOpportunitiesToTelegram(
  opportunities: Opportunity[],
  customChatId?: string,
): Promise<TelegramDispatchResult> {
  const previewText = formatTelegramDigest(opportunities);

  if (opportunities.length === 0) {
    return {
      success: false,
      error: "No opportunities selected for dispatch",
      previewText,
    };
  }

  // Retrieve credentials from SQLite vault or env
  const creds = await getIntegrationCredentials<{ botToken: string; chatId: string }>(
    undefined,
    "telegram",
  );

  const botToken = creds?.botToken || process.env.TELEGRAM_BOT_TOKEN;
  const chatId = customChatId || creds?.chatId || process.env.TELEGRAM_CHAT_ID;

  if (!botToken || !chatId) {
    return {
      success: false,
      error: "Telegram credentials missing. Please configure Telegram in Settings -> Integrations.",
      previewText,
    };
  }

  try {
    const res = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: chatId,
        text: previewText,
        parse_mode: "Markdown",
        disable_web_page_preview: true,
      }),
    });

    const data = await res.json();
    if (!res.ok || !data.ok) {
      throw new Error(data.description || `HTTP ${res.status}`);
    }

    // Record in SQLite telegram_messages table
    const dispatchId = `tg-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 5)}`;
    const now = new Date().toISOString();

    db.insert(telegramMessagesTable)
      .values({
        id: dispatchId,
        chatId,
        messageText: previewText,
        opportunityIds: JSON.stringify(opportunities.map((o) => o.id)),
        status: "sent",
        sentAt: now,
      })
      .run();

    return {
      success: true,
      messageId: String(data.result?.message_id || dispatchId),
      previewText,
    };
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    console.error("[telegram-dispatch] Error sending to Telegram:", errMsg);
    return {
      success: false,
      error: `Telegram dispatch failed: ${errMsg}`,
      previewText,
    };
  }
}
